/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CountriesRouteImport } from './routes/countries'
import { Route as FlightReservationRouteImport } from './routes/flight-reservation'
import { Route as HotelBookingRouteImport } from './routes/hotel-booking'
import { Route as CountriesIndexRouteImport } from './routes/countries.index'
import { Route as CountriesSlugRouteImport } from './routes/countries.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesAttestationRouteImport } from './routes/services.attestation'
import { Route as ServicesTicketRouteImport } from './routes/services.ticket'
import { Route as ServicesVisaRouteImport } from './routes/services.visa'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesRoute = CountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightReservationRoute = FlightReservationRouteImport.update({
  id: '/flight-reservation',
  path: '/flight-reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelBookingRoute = HotelBookingRouteImport.update({
  id: '/hotel-booking',
  path: '/hotel-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesIndexRoute = CountriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CountriesRoute,
} as any)
const CountriesSlugRoute = CountriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CountriesRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAttestationRoute = ServicesAttestationRouteImport.update({
  id: '/services/attestation',
  path: '/services/attestation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesTicketRoute = ServicesTicketRouteImport.update({
  id: '/services/ticket',
  path: '/services/ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesVisaRoute = ServicesVisaRouteImport.update({
  id: '/services/visa',
  path: '/services/visa',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/countries': typeof CountriesRouteWithChildren
  '/flight-reservation': typeof FlightReservationRoute
  '/hotel-booking': typeof HotelBookingRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/services/attestation': typeof ServicesAttestationRoute
  '/services/ticket': typeof ServicesTicketRoute
  '/services/visa': typeof ServicesVisaRoute
  '/countries/': typeof CountriesIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/flight-reservation': typeof FlightReservationRoute
  '/hotel-booking': typeof HotelBookingRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/services/attestation': typeof ServicesAttestationRoute
  '/services/ticket': typeof ServicesTicketRoute
  '/services/visa': typeof ServicesVisaRoute
  '/countries': typeof CountriesIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/countries': typeof CountriesRouteWithChildren
  '/flight-reservation': typeof FlightReservationRoute
  '/hotel-booking': typeof HotelBookingRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/services/attestation': typeof ServicesAttestationRoute
  '/services/ticket': typeof ServicesTicketRoute
  '/services/visa': typeof ServicesVisaRoute
  '/countries/': typeof CountriesIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/countries'
    | '/flight-reservation'
    | '/hotel-booking'
    | '/countries/$slug'
    | '/services/attestation'
    | '/services/ticket'
    | '/services/visa'
    | '/countries/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/flight-reservation'
    | '/hotel-booking'
    | '/countries/$slug'
    | '/services/attestation'
    | '/services/ticket'
    | '/services/visa'
    | '/countries'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/countries'
    | '/flight-reservation'
    | '/hotel-booking'
    | '/countries/$slug'
    | '/services/attestation'
    | '/services/ticket'
    | '/services/visa'
    | '/countries/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CountriesRoute: typeof CountriesRouteWithChildren
  FlightReservationRoute: typeof FlightReservationRoute
  HotelBookingRoute: typeof HotelBookingRoute
  ServicesAttestationRoute: typeof ServicesAttestationRoute
  ServicesTicketRoute: typeof ServicesTicketRoute
  ServicesVisaRoute: typeof ServicesVisaRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries': {
      id: '/countries'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof CountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flight-reservation': {
      id: '/flight-reservation'
      path: '/flight-reservation'
      fullPath: '/flight-reservation'
      preLoaderRoute: typeof FlightReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel-booking': {
      id: '/hotel-booking'
      path: '/hotel-booking'
      fullPath: '/hotel-booking'
      preLoaderRoute: typeof HotelBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/': {
      id: '/countries/'
      path: '/'
      fullPath: '/countries/'
      preLoaderRoute: typeof CountriesIndexRouteImport
      parentRoute: typeof CountriesRoute
    }
    '/countries/$slug': {
      id: '/countries/$slug'
      path: '/$slug'
      fullPath: '/countries/$slug'
      preLoaderRoute: typeof CountriesSlugRouteImport
      parentRoute: typeof CountriesRoute
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/attestation': {
      id: '/services/attestation'
      path: '/services/attestation'
      fullPath: '/services/attestation'
      preLoaderRoute: typeof ServicesAttestationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ticket': {
      id: '/services/ticket'
      path: '/services/ticket'
      fullPath: '/services/ticket'
      preLoaderRoute: typeof ServicesTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/visa': {
      id: '/services/visa'
      path: '/services/visa'
      fullPath: '/services/visa'
      preLoaderRoute: typeof ServicesVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CountriesRouteChildren {
  CountriesSlugRoute: typeof CountriesSlugRoute
  CountriesIndexRoute: typeof CountriesIndexRoute
}

const CountriesRouteChildren: CountriesRouteChildren = {
  CountriesSlugRoute: CountriesSlugRoute,
  CountriesIndexRoute: CountriesIndexRoute,
}

const CountriesRouteWithChildren = CountriesRoute._addFileChildren(
  CountriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CountriesRoute: CountriesRouteWithChildren,
  FlightReservationRoute: FlightReservationRoute,
  HotelBookingRoute: HotelBookingRoute,
  ServicesAttestationRoute: ServicesAttestationRoute,
  ServicesTicketRoute: ServicesTicketRoute,
  ServicesVisaRoute: ServicesVisaRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
