import type { ArticleContent } from "@/components/ContentArticle";
import type { Faq } from "@/components/FaqSection";
import type { Country } from "@/data/countries";

export const homeArticle: ArticleContent = {
  title: "How Areera Travel and Tours plans a trip end to end",
  intro:
    "Most travel problems are paperwork problems. A missing bank page, a reservation an embassy cannot verify, a degree attested in the wrong order — each one costs weeks. Areera Travel and Tours is organised around removing those failures before they happen, and the sections below explain exactly how a file moves through our office.",
  sections: [
    {
      heading: "We start with eligibility, not with payment",
      paragraphs: [
        "The first conversation is a review, not a sale. We look at your passport validity, previous travel history, refusals if any, the purpose of your trip and who is funding it. That combination decides which visa category actually fits, and sometimes it decides that now is not the right time to apply at all — we will say so.",
        "Only when the category is clear do we quote a scope of work in writing: what we file, what you supply, what the embassy charges and what we charge. Nothing starts before you have that in hand.",
      ],
    },
    {
      heading: "Documentation is treated as the whole job",
      paragraphs: [
        "Every destination gets its own checklist, generated from the current requirements of that mission rather than a generic template. Financial documents are the most common reason for refusal, so we review statements for closing balance, salary credits, sudden deposits and the six-month history that most consulates expect.",
        "Supporting travel documents matter just as much. Embassies want to see an itinerary that is coherent: reservation dates that match the visa period, a hotel booking in the city you claim to be visiting, and a return leg that lines up with your leave letter.",
      ],
      list: [
        "Passport and photo specifications checked against the mission's own guidance",
        "Financial proof reviewed for balance, history and source of funds",
        "Employment, business or study evidence matched to your stated purpose",
        "Verifiable flight reservations and hotel bookings with real reference numbers",
        "Attestation sequencing for any educational or commercial document",
      ],
    },
    {
      heading: "Reservations that survive verification",
      paragraphs: [
        "Consulates increasingly call airlines and hotels to confirm bookings. A PDF generated by a fare aggregator will not pass that check. We issue genuine airline reservations with a live PNR and hotel bookings held under your name, so a verification call returns the answer the officer expects.",
        "After approval the same reservation converts into a confirmed ticket, which means you are not paying twice or rebuilding an itinerary under time pressure.",
      ],
    },
    {
      heading: "Attestation follows a fixed legal order",
      paragraphs: [
        "Educational and commercial documents cannot be attested out of sequence. Issuing authority verification comes first, then notarial or regional attestation where required, then the Ministry of Foreign Affairs, and only then the destination embassy. Skipping a stage means the last office rejects the document and the whole chain restarts.",
        "We track each document at each stage and tell you where it physically is, which is usually the question clients most want answered.",
      ],
    },
    {
      heading: "What we will never promise",
      paragraphs: [
        "We do not advertise approval percentages, we do not offer guaranteed visas, and we do not submit information we have not verified. Visa decisions belong to the mission and no agency can override them. What we can control is that your file is complete, consistent and submitted on time — and that is what we are accountable for.",
      ],
    },
  ],
};

export const homeFaqs: Faq[] = [
  {
    question: "Do you guarantee that my visa will be approved?",
    answer:
      "No, and you should treat any agency that does with caution. Visa decisions rest entirely with the embassy or consulate. We guarantee only that your application is complete, consistent with the mission's published requirements and submitted within the agreed timeline.",
  },
  {
    question: "How far in advance should I start my application?",
    answer:
      "For most short-stay visas, four to eight weeks before departure is comfortable. Peak seasons, missions that require biometric appointments, and files that need attestation should start eight to twelve weeks ahead because appointment availability, not processing, is usually the bottleneck.",
  },
  {
    question: "Can I get a flight reservation without buying a ticket?",
    answer:
      "Yes. We issue genuine airline reservations with a verifiable PNR for embassy submission, and convert them into confirmed tickets once your visa is approved or your plans are final.",
  },
  {
    question: "What happens if my visa is refused?",
    answer:
      "We request the refusal grounds, review them against the submitted file and advise honestly whether reapplication is sensible, what should change, and how long you should wait. Government fees are non-refundable, which is why the eligibility review comes first.",
  },
  {
    question: "Do you handle group, family and corporate travel?",
    answer:
      "Yes. Families travelling together, corporate delegations and pilgrimage groups are handled as a single coordinated file with one consultant, so dates, reservations and documentation stay aligned across all passengers.",
  },
];

export const servicesArticle: ArticleContent = {
  title: "Choosing the right service for your situation",
  intro:
    "Our five services overlap deliberately: a single trip often needs a visa file, a verifiable reservation, an attested document and a ticket. This guide explains what each service covers, when you need it and how they connect.",
  sections: [
    {
      heading: "Visa assistance",
      paragraphs: [
        "This is the full application service: eligibility review, category selection, a destination-specific checklist, form completion, appointment booking, submission and tracking through to passport handover. It suits tourist, business, student, work, family visit and medical travel.",
        "You need it when the destination requires a consular decision before travel, when you have had a previous refusal, or when your case has any complexity — self-employment, sponsored travel, a first-time passport or a short travel history.",
      ],
    },
    {
      heading: "Air ticketing",
      paragraphs: [
        "Ticketing covers domestic and international issuance across major carriers, multi-city and open-jaw routings, group fares and pilgrimage travel. We compare routing, baggage allowance and change rules rather than headline price alone, because the cheapest fare is often the one with the costliest change penalty.",
        "Tickets are issued only after you approve the itinerary in writing, so there is never a surprise on the invoice.",
      ],
    },
    {
      heading: "Document attestation",
      paragraphs: [
        "Attestation legalises a document for use abroad. Educational certificates for study or employment, personal documents such as birth and marriage certificates, and commercial paperwork for export or company registration all follow their own route through verification, MOFA and the destination embassy.",
        "Start attestation early. It is the one part of a travel plan that depends on third-party offices with their own queues, and it cannot be accelerated by paying more.",
      ],
    },
    {
      heading: "Hotel booking and flight reservation",
      paragraphs: [
        "These two exist primarily to make a visa file credible, and secondarily to make the trip comfortable. Both are issued as genuine, verifiable bookings under your name, with dates that match your visa period and itinerary.",
        "If your plans change after approval, we amend or cancel within the property's or airline's rules and tell you the cost before acting.",
      ],
      list: [
        "Applying for a visa? Start with visa assistance and add a reservation and hotel booking.",
        "Travelling for work or study abroad? Start with attestation, then the visa file.",
        "Already hold a visa? Ticketing and hotel booking are all you need.",
      ],
    },
  ],
};

export const servicesFaqs: Faq[] = [
  {
    question: "Can I use only one service, or must I book a package?",
    answer:
      "Every service is standalone. Many clients use us only for attestation or only for ticketing. We will tell you if a related service genuinely strengthens your case, but nothing is bundled by default.",
  },
  {
    question: "How are your fees structured?",
    answer:
      "Government, embassy and airline charges are passed through at cost and shown separately from our service fee. You receive the full breakdown in writing before any work begins.",
  },
  {
    question: "Do you work with clients outside our city?",
    answer:
      "Yes. Most files are handled remotely by email and WhatsApp, with couriered documents where originals are required. Biometric appointments still need you to attend in person at the relevant centre.",
  },
  {
    question: "Who will I be dealing with day to day?",
    answer:
      "One consultant owns your file from the first review to handover, so you never re-explain your case. Their direct contact details are shared when work begins.",
  },
];

export const visaArticle: ArticleContent = {
  title: "Understanding the visa process before you apply",
  intro:
    "A visa application is an argument made with documents: that you have a genuine reason to travel, the means to fund it, and reasons to return. Everything below explains how consulates read that argument and how we build it.",
  sections: [
    {
      heading: "Ties to your home country carry the most weight",
      paragraphs: [
        "Officers assessing a short-stay application are mainly judging immigration risk. Stable employment, a running business, property, family dependents and a history of returning from previous trips all reduce it. Applicants with none of these are not disqualified, but their file needs to explain the situation directly rather than hope it goes unnoticed.",
      ],
    },
    {
      heading: "How financial documents are actually assessed",
      paragraphs: [
        "A healthy closing balance deposited last week is weaker than a modest balance built steadily over six months. Consulates look for consistency, credible income, and a relationship between your stated occupation and your account activity. Large unexplained deposits invite questions, so we ask about them first and document the source.",
        "Where a sponsor funds the trip, their documents must be as complete as yours, plus written proof of the relationship and a sponsorship declaration.",
      ],
    },
    {
      heading: "Common reasons applications are refused",
      paragraphs: [
        "Refusals are rarely mysterious. In our experience they cluster into a handful of avoidable causes, which is why the review stage matters more than the submission stage.",
      ],
      list: [
        "Inconsistency between the form, the itinerary and the supporting documents",
        "Insufficient or unexplained funds relative to the trip cost",
        "Bookings the mission could not verify with the airline or hotel",
        "Weak evidence of employment, enrolment or business activity",
        "Undisclosed previous refusals or overstays discovered during checks",
        "Applying in the wrong visa category for the actual purpose of travel",
      ],
    },
    {
      heading: "Previous refusals are workable, not fatal",
      paragraphs: [
        "A prior refusal must be declared. Concealing it is treated as misrepresentation and is far more damaging than the original refusal. We review the refusal grounds, address each one explicitly in the new file with fresh evidence, and advise on the waiting period that gives the reapplication a fair hearing.",
      ],
    },
    {
      heading: "After submission",
      paragraphs: [
        "Once a file is lodged, the timeline belongs to the mission. We monitor status, respond to any request for additional documents within the deadline, and hand your passport back with the decision. If an administrative delay exceeds the published processing time, we follow up formally on your behalf.",
      ],
    },
  ],
};

export const visaFaqs: Faq[] = [
  {
    question: "How long does a tourist visa usually take?",
    answer:
      "Published processing times range from about three working days for straightforward e-visas to several weeks for missions that require appointments and additional checks. Each country page on this site lists the current published timeline for that destination.",
  },
  {
    question: "Do I have to attend in person?",
    answer:
      "It depends on the mission. Many now require biometric enrolment at a visa application centre, which only you can attend. Where a mission accepts agent submission, we lodge the file for you.",
  },
  {
    question: "Should I book flights before the visa is approved?",
    answer:
      "No. Submit a verifiable reservation instead and convert it to a ticket after approval. Buying a non-refundable ticket before a decision puts your money at the mercy of a process you do not control.",
  },
  {
    question: "How much bank balance do I need?",
    answer:
      "There is rarely a fixed number. The expectation is that your funds credibly cover the trip's cost — flights, accommodation, daily expenses — with a reasonable margin, supported by a consistent six-month history.",
  },
  {
    question: "Can you help if my case is complicated?",
    answer:
      "Yes, and complicated cases are where preparation matters most: previous refusals, self-employment, freelance income, sponsored travel, first-time travellers and applicants with limited banking history. We will tell you honestly how strong the file is before you spend on government fees.",
  },
];

export const ticketArticle: ArticleContent = {
  title: "Buying air tickets without expensive surprises",
  intro:
    "Fares are only part of the cost of a ticket. Baggage rules, change penalties, layover legality and airport transfers routinely decide which itinerary is genuinely cheaper.",
  sections: [
    {
      heading: "The cheapest fare is not always the cheapest trip",
      paragraphs: [
        "Deep-discount fare classes often carry no checked baggage, no date change, and no refund at all. Once you add a bag and one date change, they frequently cost more than the mid-tier fare on the same aircraft. We quote the total cost of your actual travel pattern, not the teaser price.",
      ],
    },
    {
      heading: "Layovers, transit visas and minimum connection times",
      paragraphs: [
        "A cheap connection is worthless if you need a transit visa you cannot obtain, or if the connection time is below the airport's published minimum. We check both before offering an itinerary, and we prefer single-ticket routings so the airline carries responsibility for a missed connection.",
      ],
    },
    {
      heading: "Groups, families and pilgrimage travel",
      paragraphs: [
        "Group bookings behave differently from individual fares: seats are held under a group PNR, names can often be finalised later, and deposits secure the price. For Umrah and pilgrimage travel we coordinate ticketing around ground arrangements so arrival and departure days line up with accommodation.",
      ],
      list: [
        "Seat and meal preferences recorded at issuance",
        "Infant and child fares applied correctly",
        "Wheelchair and special assistance requested with the airline",
        "Baggage allowance confirmed in writing per passenger",
      ],
    },
    {
      heading: "Changes, cancellations and refunds",
      paragraphs: [
        "Every ticket is governed by its fare rules. Before you pay, we tell you what a date change costs, whether the ticket is refundable, and how long a refund takes to reach you. If you need flexibility, we will show you what it costs upfront rather than after a change becomes necessary.",
      ],
    },
  ],
};

export const ticketFaqs: Faq[] = [
  {
    question: "Can I change my travel date after the ticket is issued?",
    answer:
      "Usually yes, subject to the fare rules: an airline change fee plus any difference in fare. We confirm the exact rule for your ticket before issuance so the cost is never a surprise.",
  },
  {
    question: "How soon do I receive my e-ticket?",
    answer:
      "For confirmed payments on available fares, the e-ticket is normally issued the same working day and sent by email and WhatsApp.",
  },
  {
    question: "Do you book infant and child fares?",
    answer:
      "Yes. Infants under two travelling on a lap and children with their own seat are ticketed at the applicable reduced fare, with the correct baggage entitlement noted.",
  },
  {
    question: "Is a ticket the same as a reservation for visa purposes?",
    answer:
      "No. A reservation holds the seat and produces a verifiable PNR without full payment; a ticket is the paid, issued document. Most embassies ask only for a reservation at application stage.",
  },
];

export const attestationArticle: ArticleContent = {
  title: "Attestation explained: order, timing and common mistakes",
  intro:
    "Attestation makes a document issued in one country legally recognisable in another. The process is rigid: each office only certifies the seal of the office before it, so sequence is everything.",
  sections: [
    {
      heading: "Why the order cannot be changed",
      paragraphs: [
        "The Ministry of Foreign Affairs does not verify your degree; it verifies the university's or board's seal. The destination embassy in turn verifies the Ministry's seal. If you present a document to a later office before an earlier one has certified it, the document is rejected outright and the chain has to start again.",
      ],
    },
    {
      heading: "Educational documents",
      paragraphs: [
        "Degrees and transcripts normally require verification by the issuing university or the higher education authority before anything else. That verification is the slowest stage and is entirely outside an agency's control, which is why we ask clients to begin attestation as soon as employment or admission is likely, not once the offer arrives.",
      ],
    },
    {
      heading: "Personal and commercial documents",
      paragraphs: [
        "Birth, marriage and police character certificates typically route through the issuing authority and the relevant regional office before the Ministry stage. Commercial documents such as invoices, certificates of origin and board resolutions are usually certified by a chamber of commerce first, then follow the same path.",
      ],
      list: [
        "Submit originals; most offices will not attest photocopies",
        "Names must match your passport exactly across every document",
        "Damaged, laminated or altered certificates are commonly refused",
        "Keep certified copies and scans of every stamped page",
        "Translation, where required, must itself be attested",
      ],
    },
    {
      heading: "How long it takes",
      paragraphs: [
        "A straightforward personal document can complete in a few working days. Educational documents needing university or HEC verification frequently take several weeks, and embassy stages add their own queue. We give you a stage-by-stage estimate at the start and tell you where your file is at each handover rather than only at the end.",
      ],
    },
  ],
};

export const attestationFaqs: Faq[] = [
  {
    question: "Do you need my original certificates?",
    answer:
      "Yes, almost always. Attesting offices stamp the original document. We record and photograph everything we receive and return originals with the completed attestations.",
  },
  {
    question: "Can attestation be done faster for an urgent job offer?",
    answer:
      "Only marginally. Where an office offers an official urgent counter we use it, but verification stages have fixed turnaround times that cannot be bought down. Anyone promising same-week attestation of an unverified degree is not describing the real process.",
  },
  {
    question: "Is apostille the same as attestation?",
    answer:
      "No. An apostille is a single certificate accepted between countries party to the Hague Convention. Countries outside it — including most Gulf states — require the full embassy attestation chain instead.",
  },
  {
    question: "My name is spelled differently on my degree and passport. Is that a problem?",
    answer:
      "It can be. Mismatches are a frequent cause of rejection at the embassy stage. Tell us early and we will advise whether a correction, affidavit or supporting document resolves it.",
  },
];

export const hotelArticle: ArticleContent = {
  title: "Hotel bookings that satisfy an embassy and still suit your trip",
  intro:
    "A hotel booking in a visa file does two jobs: it proves where you will stay and it must survive a verification call. Booking the wrong way fails one or both.",
  sections: [
    {
      heading: "Verifiable bookings, not screenshots",
      paragraphs: [
        "Consular staff can and do call properties to confirm a reservation exists under the applicant's name for the stated dates. We book directly or through channels that leave a traceable confirmation, so that call succeeds.",
        "Names on the booking must match passports exactly, and the dates must sit inside the visa validity you are requesting.",
      ],
    },
    {
      heading: "Matching accommodation to your itinerary",
      paragraphs: [
        "If your application says you are visiting three cities, a single hotel booking in one of them weakens the file. We build the accommodation plan to mirror the itinerary, including gaps where you are staying with family — supported by an invitation letter and the host's proof of address.",
      ],
    },
    {
      heading: "Choosing the right property",
      paragraphs: [
        "Beyond the visa file, location decides how much of your trip is spent in traffic. We weigh proximity to the places you actually intend to visit, transport links, whether breakfast and transfers are included, and cancellation terms.",
      ],
      list: [
        "Refundable rates for any booking tied to a pending visa decision",
        "Family rooms and extra-bed policies confirmed before booking",
        "Airport transfer availability for late-night arrivals",
        "Halal and dietary options where requested",
        "Written confirmation of check-in and check-out times",
      ],
    },
    {
      heading: "If your visa is refused or plans change",
      paragraphs: [
        "We prefer refundable rates for visa-linked bookings so a refusal does not also cost you the accommodation. Where only a non-refundable rate is available, we say so plainly before you commit and let you decide.",
      ],
    },
  ],
};

export const hotelFaqs: Faq[] = [
  {
    question: "Will the embassy actually check my hotel booking?",
    answer:
      "Some missions check routinely, others sample randomly. Because you cannot know in advance which applies, every booking we submit is a genuine reservation held under your name.",
  },
  {
    question: "Can I cancel after my visa is approved and book elsewhere?",
    answer:
      "If the rate is refundable, yes, within the property's cancellation window. We will tell you the deadline at the time of booking.",
  },
  {
    question: "Do you book apartments and long stays?",
    answer:
      "Yes. Serviced apartments and monthly stays are available for business travel, medical treatment and family visits, and the confirmation works for visa purposes the same way a hotel booking does.",
  },
  {
    question: "I am staying with relatives. Do I still need a booking?",
    answer:
      "Usually not for the nights you are hosted, but you will need an invitation letter, the host's identity and residence proof, and accommodation cover for any nights not spent with them.",
  },
];

export const flightArticle: ArticleContent = {
  title: "Flight reservations for visa applications: what actually counts",
  intro:
    "A dummy ticket bought from a website that generates a PDF is not a reservation. Missions verify with the airline, and an itinerary with no live booking behind it can be treated as a false document.",
  sections: [
    {
      heading: "What makes a reservation verifiable",
      paragraphs: [
        "A genuine reservation exists in the airline's own system under a PNR that can be looked up on the carrier's website or by a consular officer's call. It holds a seat for a defined period without full payment, and it expires if not ticketed.",
        "We issue reservations of that kind, with the passenger name exactly as printed in the passport and dates that match the travel window in your application.",
      ],
    },
    {
      heading: "Timing your reservation",
      paragraphs: [
        "Reservations have a ticketing deadline, so issuing one too early risks expiry before your application is even seen. We time the reservation to your submission date and extend or reissue it if processing runs long, at no additional inconvenience to you.",
      ],
    },
    {
      heading: "Reservation, ticket or refundable ticket",
      paragraphs: [
        "A handful of missions insist on a confirmed ticket rather than a reservation. Where that is the case we recommend a fully refundable fare, and we confirm the refund terms in writing before purchase.",
      ],
      list: [
        "Reservation — free-standing PNR for embassy submission, no full payment",
        "Confirmed ticket — issued and paid, required by a few missions and for travel",
        "Refundable ticket — issued and paid with a defined refund route if refused",
      ],
    },
    {
      heading: "Turning a reservation into travel",
      paragraphs: [
        "Once your visa is approved we reprice the itinerary, confirm availability and issue the ticket, keeping the routing you already declared to the embassy wherever fares allow. Keeping your travel consistent with your application is good practice at the border as well as at the consulate.",
      ],
    },
  ],
};

export const flightFaqs: Faq[] = [
  {
    question: "Is a flight reservation the same as a dummy ticket?",
    answer:
      "No. A reservation is a real booking in the airline's system with a verifiable PNR. A dummy ticket is a generated document with nothing behind it, and presenting one can be treated as misrepresentation.",
  },
  {
    question: "How long does the reservation stay valid?",
    answer:
      "Typically from a few days up to a few weeks depending on the airline and fare. We monitor the ticketing deadline and reissue before expiry if your application is still in process.",
  },
  {
    question: "Do I have to fly the exact route I reserved?",
    answer:
      "Not strictly, but keeping your actual travel close to what you declared avoids questions at the border and on future applications. Tell us if plans change so the ticket can be issued sensibly.",
  },
  {
    question: "Can you reserve multi-city and open-jaw itineraries?",
    answer:
      "Yes. Multi-city trips, open-jaw routings and onward travel from a Schengen or Gulf entry point can all be reserved and later ticketed.",
  },
];

export const aboutArticle: ArticleContent = {
  title: "How we work, and why we work this way",
  intro:
    "Areera Travel and Tours was built around a simple observation: travellers rarely lose money because of fares, they lose it because of paperwork. Our process is designed against that failure mode.",
  sections: [
    {
      heading: "One consultant, one file",
      paragraphs: [
        "Files are not passed between desks. The consultant who reviews your eligibility is the one who prepares your checklist, files your application and calls you with the outcome. It is slower to scale and considerably better for accuracy, because nobody has to reconstruct the reasoning behind a decision made last week.",
      ],
    },
    {
      heading: "Written scope before work starts",
      paragraphs: [
        "Every engagement begins with a written note covering what we will do, what you must provide, the government charges at cost, our fee, and the realistic timeline. If any of those change mid-process we tell you in writing before continuing.",
      ],
    },
    {
      heading: "Honest advice, including when it costs us the job",
      paragraphs: [
        "If your case is weak we will say so, and if a destination genuinely does not need an agency we will tell you to apply yourself. Turning away work we cannot do well is cheaper than handling the consequences of a refusal that was predictable from the start.",
      ],
    },
    {
      heading: "Confidentiality and document handling",
      paragraphs: [
        "Passports and original certificates are logged in and out, stored securely, and returned in person or by tracked courier. Your financial and personal documents are used only for the application you engaged us for, and are not shared with third parties beyond the mission and the offices in the attestation chain.",
      ],
    },
  ],
};

export const aboutFaqs: Faq[] = [
  {
    question: "How long has Areera Travel and Tours been operating?",
    answer:
      "We began as a single visa documentation desk and grew into a full travel practice covering ticketing, attestation, hotels and reservations across Asia, the Middle East and Africa.",
  },
  {
    question: "Are you an approved IATA ticketing agency?",
    answer:
      "Our ticketing is issued to IATA standards through accredited channels, so your e-ticket is a valid airline document, not a third-party voucher.",
  },
  {
    question: "What are your consultants' backgrounds?",
    answer:
      "The team combines consular documentation experience, airline ticketing and attestation coordination — the three areas where mistakes are most expensive for travellers.",
  },
  {
    question: "How do you keep my documents safe?",
    answer:
      "Originals are logged on receipt, stored in secure custody and returned against signature or tracked courier. Digital copies are kept only as long as the engagement requires.",
  },
];

export const contactArticle: ArticleContent = {
  title: "Getting a useful answer on the first reply",
  intro:
    "The more precise your first message, the more specific our first reply. Here is what helps us answer properly instead of asking three follow-up questions.",
  sections: [
    {
      heading: "What to include in your message",
      paragraphs: [
        "Tell us the destination, the purpose of travel, your approximate dates and the passport you hold. If you have travelled recently, or been refused anywhere, mention it — it changes the advice materially and it will surface later anyway.",
      ],
      list: [
        "Destination country and city",
        "Purpose: tourism, business, study, work, family visit or medical",
        "Intended travel dates and length of stay",
        "Nationality and passport validity",
        "Any previous visas, refusals or overstays",
        "Number of travellers and their relationship to you",
      ],
    },
    {
      heading: "How quickly we respond",
      paragraphs: [
        "Messages received during business hours are normally answered the same working day. Enquiries sent overnight or on our closed day are answered when the office reopens. Urgent travel within seven days is best raised by phone or WhatsApp rather than email.",
      ],
    },
    {
      heading: "Visiting the office",
      paragraphs: [
        "You are welcome to come in without an appointment during business hours, though booking a slot means a consultant is free when you arrive. Bring your passport and any existing documents so the review can be done in one sitting rather than two.",
      ],
    },
    {
      heading: "A note on unsolicited offers",
      paragraphs: [
        "We never ask for payment through personal accounts, never request your passport by courier before a written scope is agreed, and never promise guaranteed visas. If you receive a message claiming otherwise in our name, call the office number listed on this page to verify it.",
      ],
    },
  ],
};

export const contactFaqs: Faq[] = [
  {
    question: "What are your business hours?",
    answer:
      "Our published hours are listed on this page. Phone and WhatsApp are monitored throughout those hours, and email enquiries are normally answered the same working day.",
  },
  {
    question: "Do I need an appointment?",
    answer:
      "Walk-ins are welcome during business hours, but booking ahead guarantees a consultant is available and shortens the visit considerably.",
  },
  {
    question: "Can you handle everything remotely?",
    answer:
      "Largely yes. Reviews, checklists, forms and updates run over email and WhatsApp, with couriered originals where offices require them. Biometric appointments still require you in person.",
  },
  {
    question: "How do I check the status of an existing application?",
    answer:
      "Message the consultant handling your file directly, or contact the office with your reference and passport number and we will pull up the current stage.",
  },
];

export const countriesHubArticle: ArticleContent = {
  title: "How to use these destination guides",
  intro:
    "Each country page summarises the visa categories we file, the standard document set, the published processing time and the government fee, alongside links to book flights and accommodation for the same trip.",
  sections: [
    {
      heading: "Requirements change, sometimes without notice",
      paragraphs: [
        "Missions revise document lists, fees and appointment systems regularly, and rules also differ by the passport you hold. Treat these pages as an accurate starting point for planning, and let us confirm the current position with the mission before you file.",
      ],
    },
    {
      heading: "Visa-free, visa-on-arrival, e-visa and sticker visa",
      paragraphs: [
        "Visa-free entry needs no advance permission but still requires proof of onward travel and funds at the border. Visa-on-arrival is granted at the airport and can be refused there, so it is worth carrying full documentation. An e-visa is applied for and issued online. A sticker or consular visa requires an application to the mission, usually with biometrics.",
        "The category available to you depends on your nationality, which is why we ask for your passport before advising.",
      ],
    },
    {
      heading: "Planning across a region",
      paragraphs: [
        "Regional hubs group destinations by Asia, the Middle East, North Africa and Africa, which is useful when you are comparing several options with similar documentation, or building a multi-country itinerary where one visa can cover several stops.",
      ],
    },
  ],
};

export const countriesHubFaqs: Faq[] = [
  {
    question: "Are the fees shown on country pages final?",
    answer:
      "They reflect the destination's published government charge for the standard category. Visa centre service charges, courier fees, insurance and our service fee are quoted separately in your written scope.",
  },
  {
    question: "Why do processing times vary so much?",
    answer:
      "Appointment availability, seasonal volume, public holidays and additional checks all extend timelines. Published times assume a complete file with no request for further documents.",
  },
  {
    question: "Do these guides apply to every nationality?",
    answer:
      "No. Requirements depend on the passport you hold. Send us your nationality and we will confirm the exact category and document list that applies to you.",
  },
  {
    question: "My destination is not listed. Can you still help?",
    answer:
      "Very likely. The listed destinations are the ones we handle most often; contact us with your country and we will confirm whether we can file it.",
  },
];

export function countryArticle(country: Country): ArticleContent {
  return {
    title: `Applying for a ${country.name} visa`,
    intro: `${country.blurb} This guide covers how applications to ${country.name} are assessed, what to prepare beyond the basic checklist, and how the trip fits together once the visa is issued.`,
    sections: [
      {
        heading: `Choosing the right ${country.name} visa category`,
        paragraphs: [
          `${country.name} issues ${country.visaTypes.length} main categories relevant to our clients: ${country.visaTypes.join(", ")}. Applying in the wrong category is a common and entirely avoidable refusal, because the purpose stated on your form must match the evidence you file and the activity you intend to carry out.`,
          `If your trip mixes purposes — a conference plus a holiday, or study with part-time work — tell us upfront so the primary purpose is declared correctly and the supporting documents follow it.`,
        ],
      },
      {
        heading: "Preparing your documents",
        paragraphs: [
          `The core set below is what the ${country.name} mission expects from a standard applicant. We add case-specific evidence on top: invitation letters, sponsor documents, admission letters, medical appointments or company registration, depending on why you are travelling.`,
        ],
        list: country.documents,
      },
      {
        heading: "Timeline and cost",
        paragraphs: [
          `Published processing for ${country.name} runs to ${country.processingTime}, measured from a complete submission rather than from your first enquiry. Government fees are ${country.fees}, payable in addition to any visa centre charge and our service fee.`,
          `Prices inside ${country.name} are quoted in ${country.currency}, which is worth knowing when you budget for accommodation, transfers and daily expenses in ${country.capital} and beyond.`,
        ],
      },
      {
        heading: `Arriving in ${country.capital}`,
        paragraphs: [
          `Carry printed copies of your visa, hotel confirmation, return reservation and funds evidence in your hand luggage. Immigration officers at ${country.capital} can ask for any of them, and a visa grants permission to travel rather than a guaranteed right of entry.`,
          `Keep your accommodation and itinerary consistent with what you declared on the application; unexplained differences are the most common cause of secondary questioning at the border.`,
        ],
      },
    ],
  };
}

export function countryFaqs(country: Country): Faq[] {
  return [
    {
      question: `What visa types are available for ${country.name}?`,
      answer: `${country.visaTypes.join("; ")}. We confirm the exact category that fits your purpose of travel and passport before filing.`,
    },
    {
      question: `What documents are required for a ${country.name} visa?`,
      answer: `${country.documents.join("; ")}. Case-specific documents such as invitation letters, sponsor proof or admission letters may be added depending on your category.`,
    },
    {
      question: `How long does ${country.name} visa processing take?`,
      answer: `${country.processingTime}, counted from a complete submission. Appointment availability and seasonal volume can extend this, and we tell you the current position before you apply.`,
    },
    {
      question: `What is the government fee for a ${country.name} visa?`,
      answer: `${country.fees}. Visa centre service charges, courier, insurance and our service fee are quoted separately and in writing.`,
    },
    {
      question: `Can I book flights and hotels in ${country.name} before approval?`,
      answer: `We recommend verifiable reservations rather than paid bookings until the visa is issued. After approval we convert your reservation into a confirmed ticket and finalise accommodation in ${country.capital} or your onward cities.`,
    },
    {
      question: `Do I need travel insurance for ${country.name}?`,
      answer: `Several missions require insurance covering the full stay, and it is sensible even where it is not mandatory. We advise on the required cover level for ${country.name} when we send your checklist.`,
    },
  ];
}

export function regionArticle(region: string, count: number): ArticleContent {
  return {
    title: `Travelling to ${region}: what to plan for`,
    intro: `We currently cover ${count} destinations across ${region}, each with its own consular practice. These are the themes that come up on almost every ${region} file.`,
    sections: [
      {
        heading: "Documentation standards differ sharply within the region",
        paragraphs: [
          `Neighbouring countries in ${region} can take very different approaches: one may issue an e-visa in days while the next requires biometrics, attested certificates and an in-person interview. Never assume a checklist transfers from one destination to another, even for the same purpose of travel.`,
        ],
      },
      {
        heading: "Attestation and legalisation",
        paragraphs: [
          `Employment and study routes across much of ${region} require educational and personal documents to be attested through the full chain and legalised by the destination mission. Because that runs on third-party timelines, start it before the visa application rather than alongside it.`,
        ],
      },
      {
        heading: "Building a multi-country itinerary",
        paragraphs: [
          `If you plan to visit several countries in ${region} on one trip, sequence entries so that visas with the shortest validity are used first, and keep reservations consistent across the whole route. We map the itinerary against each visa's validity and permitted stay before anything is booked.`,
        ],
      },
      {
        heading: "Seasonality and appointment pressure",
        paragraphs: [
          `Holiday seasons, pilgrimage periods and local public holidays compress appointment availability across ${region} and stretch published processing times. Applying six to eight weeks ahead of peak dates is the single cheapest way to protect your travel plan.`,
        ],
      },
    ],
  };
}
